#![cfg_attr(all(windows, not(debug_assertions)), windows_subsystem = "windows")]

mod diagnostics;
mod elevation;
/// Embedded country-flag bitmaps (generated by build.rs from flags_rgba/).
/// Windows-only: it's the one platform whose fonts can't render flag emoji, so the
/// tray composites these raster flags instead. Other platforms keep native emoji.
#[cfg(target_os = "windows")]
mod flags {
    include!(concat!(env!("OUT_DIR"), "/flags_generated.rs"));
}
mod geo;
mod network;
mod platform;
mod runtime;
mod single_instance;
mod tray;
mod tun_backend;
mod types;
mod util;
mod watcher;
mod windows_recovery;

use crate::diagnostics::DiagnosticReport;
use crate::geo::{lookup_exit_status, lookup_exit_status_direct};
use proxy_core::local_socks;
use proxy_core::socks5;
#[cfg(any(target_os = "linux", target_os = "windows"))]
use proxy_core::system_local_endpoint;
use proxy_core::system_proxy;
use proxy_core::{
    parse_raw_import_text, AppConfig, ConfigError, ResolvedProfile, RoutingMode, TraySettings,
};
use std::sync::{Arc, Mutex};
use tauri::menu::{Menu, MenuItem};
use tauri::tray::TrayIconBuilder;
use tauri::{AppHandle, Emitter, Manager, State, WebviewUrl, WebviewWindowBuilder, WindowEvent};

use crate::runtime::{
    cleanup_runtime_artifacts, perform_startup_cleanup, persist_runtime_artifacts_state,
    persist_system_snapshot, stop_runtime,
};
use crate::single_instance::SingleInstanceLock;
use crate::tray::{connection_icon, update_tray_ui};
use crate::types::consts::{
    MENU_ACTION_ID, MENU_EXIT_ID, MENU_OPEN_ID, MENU_QUIT_ID, MENU_STATUS_ID, TRAY_ID,
};
use crate::types::{
    ConnectionState, NetworkSnapshot, RawImportPreview, RuntimeSnapshot, RuntimeState,
    SharedRuntimeState, Status, TrayConnectionState, TrayHandles,
};
use crate::watcher::start_exit_status_poller;

#[tauri::command]
fn load_config() -> Result<AppConfig, String> {
    load_or_default_config().map_err(|e| e.to_string())
}

#[tauri::command]
fn save_config(
    app: AppHandle,
    config: AppConfig,
    tray: State<'_, TrayHandles>,
    state: State<'_, SharedRuntimeState>,
) -> Result<String, String> {
    let config = config.canonicalized().map_err(|e| e.to_string())?;
    let path = config
        .save_default_path()
        .map(|path| path.display().to_string())
        .map_err(|e| e.to_string())?;

    // Re-render the tray indicator immediately so a changed display mode / IP prefix is
    // reflected without waiting for the next exit-IP poll (which can be minutes away).
    // Recomputed from the cached exit status — no network lookup needed.
    if let Ok(mut runtime) = state.lock() {
        runtime.exit_status.tray_text =
            geo::tray_indicator_text(&runtime.exit_status, &config.tray_settings);
        let snapshot = RuntimeSnapshot::from(&*runtime);
        update_tray_ui(&app, tray.inner(), &snapshot);
    }

    Ok(path)
}

#[tauri::command]
fn preview_raw_entries(text: String) -> Result<RawImportPreview, String> {
    let entries = parse_raw_import_text(&text).map_err(|e| e.to_string())?;
    let canonical_text = entries
        .iter()
        .map(proxy_core::format_raw_proxy_entry)
        .collect::<Vec<_>>()
        .join("\n");
    Ok(RawImportPreview {
        entries,
        canonical_text,
    })
}

// Async so the blocking daemon socket call runs off the main thread. A synchronous
// command would execute on the Tauri event loop, and this one is polled every few
// seconds — a slow/busy daemon would otherwise freeze the window controls.
#[tauri::command]
async fn status(state: State<'_, SharedRuntimeState>) -> Result<Status, String> {
    let config = load_or_default_config().map_err(|e| e.to_string())?;
    {
        let mut runtime = state
            .lock()
            .map_err(|_| "runtime lock poisoned".to_string())?;
        if runtime
            .active_profile
            .as_ref()
            .map(|profile| profile.routing_mode == RoutingMode::Tun)
            .unwrap_or(false)
        {
            sync_runtime_with_tun_status(&mut runtime);
        }
    }
    let runtime = state
        .lock()
        .map_err(|_| "runtime lock poisoned".to_string())?;
    Ok(Status {
        enabled: config.enabled,
        selected_profile_id: config.selected_profile_id.clone(),
        active_profile_id: runtime.active_profile.as_ref().map(|p| p.id.clone()),
        active_profile_name: runtime.active_profile.as_ref().map(|p| p.name.clone()),
        routing_mode: runtime
            .active_profile
            .as_ref()
            .map(|p| p.routing_mode.to_string())
            .unwrap_or_else(|| "none".to_string()),
        connection_state: runtime.connection_state,
        last_error: runtime.last_error.clone(),
        local_system_proxy_port: runtime.local_system_proxy.as_ref().map(|proxy| proxy.port),
        exit_status: runtime.exit_status.clone(),
        vpn_status: runtime.vpn_status.clone(),
        traffic_flow: runtime.traffic_flow.clone(),
    })
}

#[tauri::command]
fn start_proxy(
    app: AppHandle,
    config: AppConfig,
    profile_id: String,
    tray: State<'_, TrayHandles>,
    state: State<'_, SharedRuntimeState>,
) -> Result<(), String> {
    start_proxy_background(&app, tray.inner(), state.inner(), config, profile_id)
}

fn start_proxy_background(
    app: &AppHandle,
    tray: &TrayHandles,
    state: &SharedRuntimeState,
    config: AppConfig,
    profile_id: String,
) -> Result<(), String> {
    let config = config.canonicalized().map_err(|e| e.to_string())?;
    let profile_id = config
        .profile_by_selector(&profile_id)
        .map_err(|e| e.to_string())?
        .id
        .clone();
    let profile = config
        .resolve_profile_by_selector(Some(&profile_id))
        .map_err(|e| e.to_string())?;

    let snapshot = {
        let mut runtime = state
            .lock()
            .map_err(|_| "runtime lock poisoned".to_string())?;
        runtime.connection_state = ConnectionState::Rebinding;
        runtime.active_profile = Some(profile.clone());
        runtime.last_profile_name = Some(profile.name.clone());
        runtime.last_error = None;
        runtime.exit_status = Default::default();
        runtime.generation += 1;
        runtime.vpn_status = network::build_vpn_status(
            &profile,
            &NetworkSnapshot::default(),
            runtime.connection_state,
        );
        runtime.traffic_flow = network::build_traffic_flow(
            Some(&profile),
            &runtime.vpn_status,
            runtime.connection_state,
        );
        RuntimeSnapshot::from(&*runtime)
    };
    update_tray_ui(app, tray, &snapshot);

    let app = app.clone();
    let tray = tray.clone();
    let state = state.clone();
    std::thread::spawn(move || {
        if let Err(error) = start_proxy_impl(&app, &tray, &state, config, profile_id) {
            set_runtime_error(&app, &error);
        }
    });
    Ok(())
}

fn start_proxy_impl(
    app: &AppHandle,
    tray: &TrayHandles,
    state: &SharedRuntimeState,
    config: AppConfig,
    profile_id: String,
) -> Result<(), String> {
    let mut config = config.canonicalized().map_err(|e| e.to_string())?;
    let profile_id = config
        .profile_by_selector(&profile_id)
        .map_err(|e| e.to_string())?
        .id
        .clone();
    config.enabled = true;
    config.selected_profile_id = Some(profile_id.clone());
    config.active_profile_id = Some(profile_id.clone());
    let config = config.canonicalized().map_err(|e| e.to_string())?;
    let profile = config
        .resolve_profile_by_selector(Some(&profile_id))
        .map_err(|e| e.to_string())?;

    config.save_default_path().map_err(|e| e.to_string())?;
    stop_runtime(app, tray, state)?;

    if profile.routing_mode == RoutingMode::Tun && profile.startup_cleanup_enabled {
        let _ = perform_startup_cleanup();
    }

    {
        let mut runtime = state
            .lock()
            .map_err(|_| "runtime lock poisoned".to_string())?;
        runtime.connection_state = ConnectionState::Rebinding;
        runtime.active_profile = Some(profile.clone());
        runtime.last_profile_name = Some(profile.name.clone());
        runtime.last_error = None;
        runtime.exit_status = Default::default();
        runtime.generation += 1;
        runtime.vpn_status = network::build_vpn_status(
            &profile,
            &NetworkSnapshot::default(),
            runtime.connection_state,
        );
        runtime.traffic_flow = network::build_traffic_flow(
            Some(&profile),
            &runtime.vpn_status,
            runtime.connection_state,
        );
    }

    if profile.routing_mode == RoutingMode::System {
        #[cfg(any(target_os = "linux", target_os = "windows"))]
        let local_server = Some(
            local_socks::start(profile.endpoint.clone()).map_err(|error| {
                let message = error.to_string();
                if let Ok(mut runtime) = state.lock() {
                    runtime.connection_state = ConnectionState::Error;
                    runtime.last_error = Some(message.clone());
                    let snap = RuntimeSnapshot::from(&*runtime);
                    update_tray_ui(app, tray, &snap);
                }
                message
            })?,
        );
        #[cfg(not(any(target_os = "linux", target_os = "windows")))]
        let local_server: Option<proxy_core::LocalSocksServer> = None;

        let snapshot = match system_proxy::enable(&profile) {
            Ok(snapshot) => snapshot,
            Err(error) => {
                if let Some(proxy) = local_server {
                    let _ = proxy.shutdown();
                }
                let message = error.to_string();
                if let Ok(mut runtime) = state.lock() {
                    runtime.connection_state = ConnectionState::Error;
                    runtime.last_error = Some(message.clone());
                    let snap = RuntimeSnapshot::from(&*runtime);
                    update_tray_ui(app, tray, &snap);
                }
                return Err(message);
            }
        };

        // Persist the snapshot so we can restore it after a crash.
        persist_system_snapshot(&snapshot);

        let effective_system_profile = effective_system_lookup_profile(&profile, true);
        let runtime_snapshot = {
            let mut runtime = state
                .lock()
                .map_err(|_| "runtime lock poisoned".to_string())?;
            runtime.system_snapshot = Some(snapshot);
            #[cfg(any(target_os = "linux", target_os = "windows"))]
            if let Some(proxy) = local_server {
                runtime.local_system_proxy = Some(crate::types::LocalSystemProxyRuntime {
                    port: proxy.listen_addr().port(),
                    handle: proxy,
                });
            }
            runtime.connection_state = ConnectionState::Connected;
            runtime.vpn_status = network::build_vpn_status(
                &profile,
                &NetworkSnapshot::default(),
                runtime.connection_state,
            );
            runtime.traffic_flow = network::build_traffic_flow(
                Some(&profile),
                &runtime.vpn_status,
                runtime.connection_state,
            );
            RuntimeSnapshot::from(&*runtime)
        };
        update_tray_ui(app, tray, &runtime_snapshot);

        // Start the exit-status poller for system mode too (state is Connected
        // at this point so the first lookup fires immediately).
        if config.tray_settings.exit_ip_lookup_enabled {
            let generation = {
                let runtime = state
                    .lock()
                    .map_err(|_| "runtime lock poisoned".to_string())?;
                runtime.generation
            };
            start_exit_status_poller(
                app.clone(),
                tray.clone(),
                state.clone(),
                effective_system_profile,
                config.tray_settings.clone(),
                generation,
            )?;
        }
    } else if profile.routing_mode == RoutingMode::Tun {
        #[cfg(target_os = "windows")]
        if !elevation::is_elevated() {
            return Err(
                "Windows TUN routing requires an elevated administrator session. Start the app as administrator before connecting a TUN profile."
                    .to_string(),
            );
        }

        #[cfg(target_os = "windows")]
        guard_windows_wireguard_killswitch()?;

        let generation = {
            let runtime = state
                .lock()
                .map_err(|_| "runtime lock poisoned".to_string())?;
            runtime.generation
        };

        if config.tray_settings.exit_ip_lookup_enabled {
            start_exit_status_poller(
                app.clone(),
                tray.clone(),
                state.clone(),
                profile.clone(),
                config.tray_settings.clone(),
                generation,
            )?;
        }

        #[cfg(target_os = "windows")]
        let mut recovery_watchdog = Some(windows_recovery::TunRecoveryWatchdog::arm(
            &proxy_core::tun::tun_device_name(&profile.id),
        )?);

        let status = match tun_backend::start(profile.clone()) {
            Ok(status) => status,
            Err(error) => {
                #[cfg(target_os = "windows")]
                if let Some(watchdog) = recovery_watchdog.take() {
                    let _ = watchdog.cancel();
                }
                return Err(error.to_string());
            }
        };
        let connected_artifacts = if status.state == "connected" {
            let session_id = crate::util::generate_session_id();
            match crate::types::RuntimeArtifacts::new(
                &session_id,
                &profile,
                status.tun2proxy_pid.unwrap_or_default(),
                status.host_vpn_interface.clone(),
                status.pinned_proxy_routes.clone(),
                status.wfp_filters.clone(),
            )
            .map_err(|error| error.to_string())
            .and_then(|artifacts| {
                persist_runtime_artifacts_state(&profile, &artifacts)?;
                Ok(artifacts)
            }) {
                Ok(artifacts) => Some(artifacts),
                Err(error) => {
                    let _ = tun_backend::stop();
                    #[cfg(target_os = "windows")]
                    if let Some(watchdog) = recovery_watchdog.take() {
                        let _ = watchdog.cancel();
                    }
                    return Err(error);
                }
            }
        } else {
            #[cfg(target_os = "windows")]
            if let Some(watchdog) = recovery_watchdog.take() {
                let _ = watchdog.cancel();
            }
            None
        };
        let runtime_snapshot = {
            let mut runtime = state
                .lock()
                .map_err(|_| "runtime lock poisoned".to_string())?;
            apply_tun_daemon_status(&mut runtime, &status);
            if let Some(artifacts) = connected_artifacts {
                runtime.current_session_id = Some(artifacts.session_id.clone());
                runtime.runtime_artifacts = Some(artifacts);
                #[cfg(target_os = "windows")]
                {
                    runtime.windows_recovery_watchdog = recovery_watchdog.take();
                }
            }
            RuntimeSnapshot::from(&*runtime)
        };
        update_tray_ui(app, tray, &runtime_snapshot);
    }

    Ok(())
}

// Async: stop tears down the daemon TUN session (blocking socket I/O), so keep it off
// the event loop to avoid freezing the window during disconnect.
#[tauri::command]
async fn stop_proxy(
    app: AppHandle,
    tray: State<'_, TrayHandles>,
    state: State<'_, SharedRuntimeState>,
) -> Result<(), String> {
    stop_proxy_impl(&app, tray.inner(), state.inner())
}

fn stop_proxy_impl(
    app: &AppHandle,
    tray: &TrayHandles,
    state: &SharedRuntimeState,
) -> Result<(), String> {
    let mut config = load_or_default_config().map_err(|e| e.to_string())?;
    config.enabled = false;
    if config.selected_profile_id.is_none() {
        config.selected_profile_id = config.active_profile_id.clone();
    }
    config.save_default_path().map_err(|e| e.to_string())?;
    stop_runtime(app, tray, state)?;
    refresh_direct_exit_status_background(
        app.clone(),
        tray.clone(),
        state.clone(),
        config.tray_settings.clone(),
    );
    Ok(())
}

// Async: performs a network SOCKS5 handshake.
#[tauri::command]
async fn test_proxy(config: AppConfig, profile_id: String) -> Result<(), String> {
    let config = config.canonicalized().map_err(|e| e.to_string())?;
    let profile = config
        .resolve_profile_by_selector(Some(&profile_id))
        .map_err(|e| e.to_string())?;
    socks5::handshake(&profile.endpoint)
}

// Async: runs the exit-IP and geo network lookups.
#[tauri::command]
async fn refresh_exit_status(
    app: AppHandle,
    config: AppConfig,
    tray: State<'_, TrayHandles>,
    state: State<'_, SharedRuntimeState>,
) -> Result<crate::types::ExitStatus, String> {
    refresh_exit_status_impl(&app, tray.inner(), state.inner(), config)
}

fn refresh_exit_status_impl(
    app: &AppHandle,
    tray: &TrayHandles,
    state: &SharedRuntimeState,
    config: AppConfig,
) -> Result<crate::types::ExitStatus, String> {
    let config = config.canonicalized().map_err(|e| e.to_string())?;
    let selector = config
        .active_profile_id
        .as_deref()
        .or(config.selected_profile_id.as_deref());
    let profile = config
        .resolve_profile_by_selector(selector)
        .map_err(|e| e.to_string())?;
    let (profile, use_direct_lookup) = {
        let runtime = state
            .lock()
            .map_err(|_| "runtime lock poisoned".to_string())?;
        (
            effective_system_lookup_profile(&profile, runtime.local_system_proxy.is_some()),
            runtime.connection_state == ConnectionState::Stopped,
        )
    };
    let exit_status = if use_direct_lookup {
        lookup_exit_status_direct(&config.tray_settings)
    } else {
        lookup_exit_status(&profile, &config.tray_settings)
    };
    let snapshot = {
        let mut runtime = state
            .lock()
            .map_err(|_| "runtime lock poisoned".to_string())?;
        runtime.exit_status = exit_status.clone();
        RuntimeSnapshot::from(&*runtime)
    };
    update_tray_ui(app, tray, &snapshot);
    Ok(exit_status)
}

fn effective_system_lookup_profile(
    profile: &ResolvedProfile,
    local_proxy_active: bool,
) -> ResolvedProfile {
    #[cfg(not(any(target_os = "linux", target_os = "windows")))]
    let _ = local_proxy_active;

    #[cfg(any(target_os = "linux", target_os = "windows"))]
    if profile.routing_mode == RoutingMode::System && local_proxy_active {
        let mut effective = profile.clone();
        effective.endpoint = system_local_endpoint();
        return effective;
    }

    profile.clone()
}

// Async: diagnostics run a series of blocking network/route probes.
#[tauri::command]
async fn run_diagnostics(
    app: AppHandle,
    config: AppConfig,
    state: State<'_, SharedRuntimeState>,
) -> Result<DiagnosticReport, String> {
    diagnostics::run_diagnostics(state.inner(), config, move |event| {
        let _ = app.emit("diagnostics-progress", event);
    })
}

#[tauri::command]
fn list_desktop_apps() -> Result<Vec<proxy_core::desktop_entry::DesktopAppEntry>, String> {
    proxy_core::desktop_entry::discover_desktop_apps().map_err(|error| error.to_string())
}

#[tauri::command]
fn open_manage_window(app: AppHandle) -> Result<(), String> {
    ensure_manage_window(&app).map_err(|e| e.to_string())?;
    if let Some(window) = app.get_webview_window("manage") {
        let _ = window.show();
        let _ = window.set_focus();
    }
    Ok(())
}

fn main() {
    if handle_headless_command() {
        return;
    }
    #[cfg(target_os = "windows")]
    elevation::relaunch_elevated_if_needed();
    #[cfg(target_os = "windows")]
    std::env::set_var(proxy_platform_windows::ENABLE_WFP_MUTATION_ENV, "1");
    init_logging();
    let instance_lock = match SingleInstanceLock::acquire() {
        Ok(lock) => lock,
        Err(error) => {
            eprintln!("{error}");
            std::process::exit(0);
        }
    };

    tauri::Builder::default()
        .manage(Arc::new(Mutex::new(RuntimeState::default())))
        .manage(instance_lock)
        .setup(|app| {
            if let Err(error) = perform_startup_cleanup() {
                tracing::warn!(error = %error, "startup cleanup failed");
            }
            ensure_manage_window(app.handle())?;

            let status_item = MenuItem::with_id(
                app,
                MENU_STATUS_ID,
                "Status: Disconnected (no profile)",
                false,
                None::<&str>,
            )?;
            let exit_item =
                MenuItem::with_id(app, MENU_EXIT_ID, "Exit IP: —", false, None::<&str>)?;
            let action_item =
                MenuItem::with_id(app, MENU_ACTION_ID, "Connect", true, None::<&str>)?;
            let open = MenuItem::with_id(app, MENU_OPEN_ID, "Open Settings", true, None::<&str>)?;
            let quit = MenuItem::with_id(app, MENU_QUIT_ID, "Quit", true, None::<&str>)?;
            let menu =
                Menu::with_items(app, &[&status_item, &exit_item, &action_item, &open, &quit])?;

            TrayIconBuilder::with_id(TRAY_ID)
                .icon(connection_icon(TrayConnectionState::Disconnected, false))
                .menu(&menu)
                .show_menu_on_left_click(true)
                .on_menu_event(|app, event| match event.id().as_ref() {
                    MENU_ACTION_ID => {
                        let state = app.state::<SharedRuntimeState>();
                        let is_active = {
                            let runtime = state.lock().unwrap_or_else(|p| p.into_inner());
                            matches!(
                                runtime.connection_state,
                                ConnectionState::Connected
                                    | ConnectionState::Blocked
                                    | ConnectionState::Rebinding
                            )
                        };
                        let tray = app.state::<TrayHandles>();
                        if is_active {
                            if let Err(error) = stop_proxy_impl(app, tray.inner(), state.inner()) {
                                set_runtime_error(app, &error);
                            }
                        } else if let Err(error) = start_saved_active_profile(app) {
                            set_runtime_error(app, &error);
                        }
                    }
                    MENU_OPEN_ID => {
                        let _ = open_manage_window(app.clone());
                    }
                    MENU_QUIT_ID => app.exit(0),
                    _ => {}
                })
                .build(app)?;

            app.manage(TrayHandles {
                status_item,
                exit_item,
                action_item,
            });

            let runtime_state = app.state::<SharedRuntimeState>();
            let tray = app.state::<TrayHandles>();
            let snapshot = {
                let runtime = runtime_state
                    .lock()
                    .map_err(|_| "runtime lock poisoned")
                    .expect("runtime lock poisoned");
                RuntimeSnapshot::from(&*runtime)
            };
            update_tray_ui(app.handle(), tray.inner(), &snapshot);
            refresh_direct_exit_status_background(
                app.handle().clone(),
                tray.inner().clone(),
                runtime_state.inner().clone(),
                load_or_default_config()
                    .map(|config| config.tray_settings)
                    .unwrap_or_default(),
            );

            if let Some(window) = app.get_webview_window("manage") {
                let w = window.clone();
                window.on_window_event(move |event| {
                    if let WindowEvent::CloseRequested { api, .. } = event {
                        let _ = w.hide();
                        api.prevent_close();
                    }
                });
            }

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            load_config,
            save_config,
            preview_raw_entries,
            start_proxy,
            stop_proxy,
            status,
            test_proxy,
            refresh_exit_status,
            run_diagnostics,
            list_desktop_apps,
            open_manage_window
        ])
        .run(tauri::generate_context!())
        .expect("failed to run SOCKS5 Proxy");
}

fn handle_headless_command() -> bool {
    let mut args = std::env::args();
    let _ = args.next();
    let command = args.next();
    #[cfg_attr(not(target_os = "windows"), allow(unused_variables))]
    let rest = args.collect::<Vec<_>>();
    match command.as_deref() {
        Some("--windows-tun-preflight-json") => {
            #[cfg(target_os = "windows")]
            {
                print_windows_tun_preflight_json();
            }
            #[cfg(not(target_os = "windows"))]
            {
                println!(
                    "{}",
                    serde_json::json!({
                        "ok": false,
                        "error": "windows TUN preflight is only available on Windows"
                    })
                );
            }
            true
        }
        Some("--windows-wfp-rollback-json") => {
            #[cfg(target_os = "windows")]
            {
                print_windows_wfp_rollback_json();
            }
            #[cfg(not(target_os = "windows"))]
            {
                println!(
                    "{}",
                    serde_json::json!({
                        "ok": false,
                        "error": "windows WFP rollback is only available on Windows"
                    })
                );
            }
            true
        }
        Some("--windows-wfp-apply-json") => {
            #[cfg(target_os = "windows")]
            {
                let proxy_ip = headless_arg_value(&rest, "--proxy-ip");
                print_windows_wfp_apply_json(proxy_ip.as_deref());
            }
            #[cfg(not(target_os = "windows"))]
            {
                println!(
                    "{}",
                    serde_json::json!({
                        "ok": false,
                        "error": "windows WFP apply is only available on Windows"
                    })
                );
            }
            true
        }
        Some("--windows-wfp-wintun-selftest-json") => {
            #[cfg(target_os = "windows")]
            {
                let proxy_ip = headless_arg_value(&rest, "--proxy-ip");
                let interface = headless_arg_value(&rest, "--interface");
                print_windows_wfp_wintun_selftest_json(proxy_ip.as_deref(), interface.as_deref());
            }
            #[cfg(not(target_os = "windows"))]
            {
                println!(
                    "{}",
                    serde_json::json!({
                        "ok": false,
                        "error": "windows WFP Wintun self-test is only available on Windows"
                    })
                );
            }
            true
        }
        Some("--windows-tun-session-e2e-json") => {
            #[cfg(target_os = "windows")]
            {
                let hold_seconds = headless_arg_value(&rest, "--hold-seconds")
                    .and_then(|value| value.parse::<u64>().ok())
                    .unwrap_or(8);
                let probe_url = headless_arg_value(&rest, "--probe-url")
                    .unwrap_or_else(|| "https://api.ipify.org".to_string());
                let profile_selector = headless_arg_value(&rest, "--profile");
                print_windows_tun_session_e2e_json(
                    hold_seconds,
                    &probe_url,
                    profile_selector.as_deref(),
                );
            }
            #[cfg(not(target_os = "windows"))]
            {
                println!(
                    "{}",
                    serde_json::json!({
                        "ok": false,
                        "error": "windows TUN session end-to-end test is only available on Windows"
                    })
                );
            }
            true
        }
        Some("--windows-tun-status-poll-json") => {
            #[cfg(target_os = "windows")]
            {
                let polls = headless_arg_value(&rest, "--polls")
                    .and_then(|value| value.parse::<u32>().ok())
                    .unwrap_or(8);
                let interval = headless_arg_value(&rest, "--interval-ms")
                    .and_then(|value| value.parse::<u64>().ok())
                    .unwrap_or(1500);
                let profile_selector = headless_arg_value(&rest, "--profile");
                print_windows_tun_status_poll_json(polls, interval, profile_selector.as_deref());
            }
            #[cfg(not(target_os = "windows"))]
            {
                println!(
                    "{}",
                    serde_json::json!({
                        "ok": false,
                        "error": "windows TUN status poll test is only available on Windows"
                    })
                );
            }
            true
        }
        Some("--help") | Some("-h") => {
            println!(
                "SOCKS5Proxy desktop\n\nOptions:\n  --windows-tun-preflight-json\n  --windows-wfp-rollback-json\n  --windows-wfp-apply-json [--proxy-ip <ip>]\n  --windows-wfp-wintun-selftest-json --interface <name> [--proxy-ip <ip>]\n  --windows-tun-session-e2e-json [--profile <id|name>] [--hold-seconds <n>] [--probe-url <url>]\n  --windows-tun-status-poll-json [--profile <id|name>] [--polls <n>] [--interval-ms <ms>]"
            );
            true
        }
        _ => false,
    }
}

#[cfg_attr(not(target_os = "windows"), allow(dead_code))]
fn headless_arg_value(args: &[String], name: &str) -> Option<String> {
    args.windows(2)
        .find(|pair| pair[0] == name)
        .map(|pair| pair[1].clone())
}

#[cfg(target_os = "windows")]
fn print_windows_tun_preflight_json() {
    let preflight = proxy_platform_windows::preflight();
    let mullvad = proxy_platform_windows::mullvad_status();
    let wireguard = proxy_platform_windows::wireguard_status();
    let firewall = proxy_platform_windows::firewall_preflight();
    let wfp_exception_plan = proxy_platform_windows::wfp_exception_plan(&mullvad, &firewall);
    let wfp_operation_plan = proxy_platform_windows::wfp_operation_plan(&wfp_exception_plan);
    let wfp_apply_context = proxy_platform_windows::wfp_apply_context_for_mullvad_with_paths(
        None,
        &mullvad,
        wfp_exception_plan.app_path.clone(),
        wfp_exception_plan.tun2proxy_path.clone(),
    );
    let wfp_apply_readiness = proxy_platform_windows::wfp_apply_readiness_with_context(
        &wfp_exception_plan,
        &wfp_operation_plan,
        &wfp_apply_context,
    );
    let z4_guard = windows_z4_guard_json(&mullvad);
    let current_exe = std::env::current_exe()
        .ok()
        .map(|path| path.display().to_string());
    let current_dir = std::env::current_dir()
        .ok()
        .map(|path| path.display().to_string());
    println!(
        "{}",
        serde_json::json!({
            "ok": preflight.missing_reasons.is_empty(),
            "current_exe": current_exe,
            "current_dir": current_dir,
            "elevated": preflight.elevated,
            "tun2proxy_path": preflight.tun2proxy_path.map(|path| path.display().to_string()),
            "wintun_path": preflight.wintun_path.map(|path| path.display().to_string()),
            "missing_reasons": preflight.missing_reasons,
            "mullvad": {
                "cli_path": mullvad.cli_path.as_ref().map(|path| path.display().to_string()),
                "state": mullvad.state,
                "visible_location": mullvad.visible_location,
                "visible_ipv4": mullvad.visible_ipv4,
                "visible_ipv6": mullvad.visible_ipv6,
                "mullvad_exit_ip": mullvad.mullvad_exit_ip,
                "locked_down": mullvad.locked_down,
                "endpoint_address": mullvad.endpoint_address,
                "endpoint_ip": mullvad.endpoint_ip,
                "endpoint_port": mullvad.endpoint_port,
                "endpoint_protocol": mullvad.endpoint_protocol,
                "tunnel_interface": mullvad.tunnel_interface,
                "relay_hostname": mullvad.relay_hostname,
                "relay_ipv4": mullvad.relay_ipv4,
                "relay_ipv6": mullvad.relay_ipv6,
                "entry_hostname": mullvad.entry_hostname,
                "entry_ipv4": mullvad.entry_ipv4,
                "entry_ipv6": mullvad.entry_ipv6,
                "bridge_hostname": mullvad.bridge_hostname,
                "obfuscator_hostname": mullvad.obfuscator_hostname,
                "tunnel_protocol": mullvad.tunnel_protocol,
                "error": mullvad.error,
            },
            "wireguard": {
                "cli_path": wireguard.cli_path.as_ref().map(|path| path.display().to_string()),
                "interfaces": wireguard.interfaces,
                "endpoint_ips": wireguard.endpoint_ips,
                "locked_down": wireguard.locked_down,
                "lockdown_reason": wireguard.lockdown_reason,
                "error": wireguard.error,
            },
            "firewall": {
                "elevated": firewall.elevated,
                "firewall_profiles_count": firewall.firewall_profiles_count,
                "matching_firewall_rule_count": firewall.matching_firewall_rule_count,
                "wfp_state_available": firewall.wfp_state_available,
                "wfp_state_error": firewall.wfp_state_error,
                "error": firewall.error,
            },
            "wfp_exception_plan": {
                "required": wfp_exception_plan.required,
                "ready": wfp_exception_plan.ready,
                "status": wfp_exception_plan.status,
                "blockers": wfp_exception_plan.blockers,
                "warnings": wfp_exception_plan.warnings,
                "app_path": wfp_exception_plan.app_path.as_ref().map(|path| path.display().to_string()),
                "tun2proxy_path": wfp_exception_plan.tun2proxy_path.as_ref().map(|path| path.display().to_string()),
                "mullvad_tunnel_interface": wfp_exception_plan.mullvad_tunnel_interface,
                "mullvad_endpoint_ip": wfp_exception_plan.mullvad_endpoint_ip,
                "planned_allows": wfp_exception_plan.planned_allows,
                "planned_cleanup": wfp_exception_plan.planned_cleanup,
                "planned_filter_identities": wfp_exception_plan.planned_filter_identities.iter().map(|identity| {
                    serde_json::json!({
                        "role": identity.role,
                        "key": identity.key,
                        "display_name": identity.display_name,
                        "layer": identity.layer,
                    })
                }).collect::<Vec<_>>(),
                "session_tag": wfp_exception_plan.session_tag,
            },
            "wfp_operation_plan": {
                "required": wfp_operation_plan.required,
                "ready": wfp_operation_plan.ready,
                "status": wfp_operation_plan.status,
                "blockers": wfp_operation_plan.blockers,
                "session_tag": wfp_operation_plan.session_tag,
                "cleanup_before_apply": wfp_operation_plan.cleanup_before_apply.iter().map(|operation| {
                    serde_json::json!({
                        "action": operation.action,
                        "role": operation.role,
                        "key": operation.key,
                        "layer": operation.layer,
                        "display_name": operation.display_name,
                        "scope": operation.scope,
                    })
                }).collect::<Vec<_>>(),
                "apply_operations": wfp_operation_plan.apply_operations.iter().map(|operation| {
                    serde_json::json!({
                        "action": operation.action,
                        "role": operation.role,
                        "key": operation.key,
                        "layer": operation.layer,
                        "display_name": operation.display_name,
                        "scope": operation.scope,
                    })
                }).collect::<Vec<_>>(),
                "rollback_operations": wfp_operation_plan.rollback_operations.iter().map(|operation| {
                    serde_json::json!({
                        "action": operation.action,
                        "role": operation.role,
                        "key": operation.key,
                        "layer": operation.layer,
                        "display_name": operation.display_name,
                        "scope": operation.scope,
                    })
                }).collect::<Vec<_>>(),
                "expected_runtime_filters": wfp_operation_plan.expected_runtime_filters,
            },
            "wfp_apply_readiness": {
                "required": wfp_apply_readiness.required,
                "ready": wfp_apply_readiness.ready,
                "status": wfp_apply_readiness.status,
                "context": {
                    "proxy_ip": wfp_apply_readiness.context.proxy_ip.as_ref(),
                    "proxy_ip_error": wfp_apply_readiness.context.proxy_ip_error.as_ref(),
                    "app_path": wfp_apply_readiness.context.app_path.as_ref().map(|path| path.display().to_string()),
                    "tun2proxy_path": wfp_apply_readiness.context.tun2proxy_path.as_ref().map(|path| path.display().to_string()),
                    "mullvad_tunnel_interface": wfp_apply_readiness.context.mullvad_tunnel_interface.as_ref(),
                    "mullvad_tunnel_interface_index": wfp_apply_readiness.context.mullvad_tunnel_interface_index,
                    "mullvad_tunnel_interface_index_error": wfp_apply_readiness.context.mullvad_tunnel_interface_index_error.as_ref(),
                    "mullvad_endpoint_ip": wfp_apply_readiness.context.mullvad_endpoint_ip.as_ref(),
                    "mullvad_endpoint_ip_error": wfp_apply_readiness.context.mullvad_endpoint_ip_error.as_ref(),
                },
                "blockers": wfp_apply_readiness.blockers,
                "role_specs": wfp_apply_readiness.role_specs.iter().map(|spec| {
                    serde_json::json!({
                        "role": spec.role,
                        "key": spec.key,
                        "layer": spec.layer,
                        "display_name": spec.display_name,
                        "ready": spec.ready,
                        "conditions": spec.conditions,
                        "blockers": spec.blockers,
                    })
                }).collect::<Vec<_>>(),
            },
            "z4_guard": z4_guard,
        })
    );
}

#[cfg(target_os = "windows")]
fn print_windows_wfp_rollback_json() {
    let mullvad = proxy_platform_windows::mullvad_status();
    let firewall = proxy_platform_windows::firewall_preflight();
    let wfp_exception_plan = proxy_platform_windows::wfp_exception_plan(&mullvad, &firewall);
    let wfp_operation_plan = proxy_platform_windows::wfp_operation_plan(&wfp_exception_plan);
    let wfp_apply_context = proxy_platform_windows::wfp_apply_context_for_mullvad_with_paths(
        None,
        &mullvad,
        wfp_exception_plan.app_path.clone(),
        wfp_exception_plan.tun2proxy_path.clone(),
    );
    let wfp_apply_readiness = proxy_platform_windows::wfp_apply_readiness_with_context(
        &wfp_exception_plan,
        &wfp_operation_plan,
        &wfp_apply_context,
    );
    let report = proxy_platform_windows::rollback_wfp_operation_plan(&wfp_operation_plan);
    let current_exe = std::env::current_exe()
        .ok()
        .map(|path| path.display().to_string());
    println!(
        "{}",
        match report {
            Ok(report) => serde_json::json!({
                "ok": report.errors.is_empty(),
                "current_exe": current_exe,
                "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV,
                "operation_plan_status": wfp_operation_plan.status,
                "operation_plan_required": wfp_operation_plan.required,
                "operation_plan_ready": wfp_operation_plan.ready,
                "rollback_operation_count": wfp_operation_plan.rollback_operations.len(),
                "expected_runtime_filter_count": wfp_operation_plan.expected_runtime_filters.len(),
                "apply_readiness_status": wfp_apply_readiness.status,
                "apply_readiness_ready": wfp_apply_readiness.ready,
                "apply_readiness_context": {
                    "proxy_ip": wfp_apply_readiness.context.proxy_ip.as_ref(),
                    "proxy_ip_error": wfp_apply_readiness.context.proxy_ip_error.as_ref(),
                    "app_path": wfp_apply_readiness.context.app_path.as_ref().map(|path| path.display().to_string()),
                    "tun2proxy_path": wfp_apply_readiness.context.tun2proxy_path.as_ref().map(|path| path.display().to_string()),
                    "mullvad_tunnel_interface": wfp_apply_readiness.context.mullvad_tunnel_interface.as_ref(),
                    "mullvad_tunnel_interface_index": wfp_apply_readiness.context.mullvad_tunnel_interface_index,
                    "mullvad_tunnel_interface_index_error": wfp_apply_readiness.context.mullvad_tunnel_interface_index_error.as_ref(),
                    "mullvad_endpoint_ip": wfp_apply_readiness.context.mullvad_endpoint_ip.as_ref(),
                    "mullvad_endpoint_ip_error": wfp_apply_readiness.context.mullvad_endpoint_ip_error.as_ref(),
                },
                "apply_readiness_blockers": wfp_apply_readiness.blockers,
                "apply_readiness_role_specs": wfp_apply_readiness.role_specs.iter().map(|spec| {
                    serde_json::json!({
                        "role": spec.role,
                        "key": spec.key,
                        "layer": spec.layer,
                        "display_name": spec.display_name,
                        "ready": spec.ready,
                        "conditions": spec.conditions,
                        "blockers": spec.blockers,
                    })
                }).collect::<Vec<_>>(),
                "report": {
                    "attempted": report.attempted,
                    "status": report.status,
                    "blockers": report.blockers,
                    "applied": report.applied,
                    "deleted": report.deleted,
                    "errors": report.errors,
                }
            }),
            Err(error) => serde_json::json!({
                "ok": false,
                "current_exe": current_exe,
                "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV,
                "operation_plan_status": wfp_operation_plan.status,
                "operation_plan_required": wfp_operation_plan.required,
                "operation_plan_ready": wfp_operation_plan.ready,
                "rollback_operation_count": wfp_operation_plan.rollback_operations.len(),
                "expected_runtime_filter_count": wfp_operation_plan.expected_runtime_filters.len(),
                "apply_readiness_status": wfp_apply_readiness.status,
                "apply_readiness_ready": wfp_apply_readiness.ready,
                "apply_readiness_context": {
                    "proxy_ip": wfp_apply_readiness.context.proxy_ip.as_ref(),
                    "proxy_ip_error": wfp_apply_readiness.context.proxy_ip_error.as_ref(),
                    "app_path": wfp_apply_readiness.context.app_path.as_ref().map(|path| path.display().to_string()),
                    "tun2proxy_path": wfp_apply_readiness.context.tun2proxy_path.as_ref().map(|path| path.display().to_string()),
                    "mullvad_tunnel_interface": wfp_apply_readiness.context.mullvad_tunnel_interface.as_ref(),
                    "mullvad_tunnel_interface_index": wfp_apply_readiness.context.mullvad_tunnel_interface_index,
                    "mullvad_tunnel_interface_index_error": wfp_apply_readiness.context.mullvad_tunnel_interface_index_error.as_ref(),
                    "mullvad_endpoint_ip": wfp_apply_readiness.context.mullvad_endpoint_ip.as_ref(),
                    "mullvad_endpoint_ip_error": wfp_apply_readiness.context.mullvad_endpoint_ip_error.as_ref(),
                },
                "apply_readiness_blockers": wfp_apply_readiness.blockers,
                "apply_readiness_role_specs": wfp_apply_readiness.role_specs.iter().map(|spec| {
                    serde_json::json!({
                        "role": spec.role,
                        "key": spec.key,
                        "layer": spec.layer,
                        "display_name": spec.display_name,
                        "ready": spec.ready,
                        "conditions": spec.conditions,
                        "blockers": spec.blockers,
                    })
                }).collect::<Vec<_>>(),
                "error": error.to_string(),
            }),
        }
    );
}

#[cfg(target_os = "windows")]
fn print_windows_wfp_apply_json(proxy_ip: Option<&str>) {
    let mullvad = proxy_platform_windows::mullvad_status();
    let firewall = proxy_platform_windows::firewall_preflight();
    let wfp_exception_plan = proxy_platform_windows::wfp_exception_plan(&mullvad, &firewall);
    let wfp_operation_plan = proxy_platform_windows::wfp_operation_plan(&wfp_exception_plan);
    let wfp_apply_context = proxy_platform_windows::wfp_apply_context_for_mullvad_with_paths(
        proxy_ip,
        &mullvad,
        wfp_exception_plan.app_path.clone(),
        wfp_exception_plan.tun2proxy_path.clone(),
    );
    let wfp_apply_readiness = proxy_platform_windows::wfp_apply_readiness_with_context(
        &wfp_exception_plan,
        &wfp_operation_plan,
        &wfp_apply_context,
    );
    let report =
        proxy_platform_windows::apply_wfp_operation_plan(&wfp_operation_plan, &wfp_apply_readiness);
    let current_exe = std::env::current_exe()
        .ok()
        .map(|path| path.display().to_string());
    println!(
        "{}",
        match report {
            Ok(report) => serde_json::json!({
                "ok": report.errors.is_empty(),
                "current_exe": current_exe,
                "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV,
                "operation_plan_status": wfp_operation_plan.status,
                "operation_plan_required": wfp_operation_plan.required,
                "operation_plan_ready": wfp_operation_plan.ready,
                "apply_operation_count": wfp_operation_plan.apply_operations.len(),
                "expected_runtime_filter_count": wfp_operation_plan.expected_runtime_filters.len(),
                "apply_readiness_status": wfp_apply_readiness.status,
                "apply_readiness_ready": wfp_apply_readiness.ready,
                "apply_readiness_context": {
                    "proxy_ip": wfp_apply_readiness.context.proxy_ip.as_ref(),
                    "proxy_ip_error": wfp_apply_readiness.context.proxy_ip_error.as_ref(),
                    "app_path": wfp_apply_readiness.context.app_path.as_ref().map(|path| path.display().to_string()),
                    "tun2proxy_path": wfp_apply_readiness.context.tun2proxy_path.as_ref().map(|path| path.display().to_string()),
                    "mullvad_tunnel_interface": wfp_apply_readiness.context.mullvad_tunnel_interface.as_ref(),
                    "mullvad_tunnel_interface_index": wfp_apply_readiness.context.mullvad_tunnel_interface_index,
                    "mullvad_tunnel_interface_index_error": wfp_apply_readiness.context.mullvad_tunnel_interface_index_error.as_ref(),
                    "mullvad_endpoint_ip": wfp_apply_readiness.context.mullvad_endpoint_ip.as_ref(),
                    "mullvad_endpoint_ip_error": wfp_apply_readiness.context.mullvad_endpoint_ip_error.as_ref(),
                },
                "apply_readiness_blockers": wfp_apply_readiness.blockers,
                "report": {
                    "attempted": report.attempted,
                    "status": report.status,
                    "blockers": report.blockers,
                    "applied": report.applied,
                    "deleted": report.deleted,
                    "errors": report.errors,
                }
            }),
            Err(error) => serde_json::json!({
                "ok": false,
                "current_exe": current_exe,
                "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV,
                "operation_plan_status": wfp_operation_plan.status,
                "operation_plan_required": wfp_operation_plan.required,
                "operation_plan_ready": wfp_operation_plan.ready,
                "apply_operation_count": wfp_operation_plan.apply_operations.len(),
                "expected_runtime_filter_count": wfp_operation_plan.expected_runtime_filters.len(),
                "apply_readiness_status": wfp_apply_readiness.status,
                "apply_readiness_ready": wfp_apply_readiness.ready,
                "apply_readiness_context": {
                    "proxy_ip": wfp_apply_readiness.context.proxy_ip.as_ref(),
                    "proxy_ip_error": wfp_apply_readiness.context.proxy_ip_error.as_ref(),
                    "app_path": wfp_apply_readiness.context.app_path.as_ref().map(|path| path.display().to_string()),
                    "tun2proxy_path": wfp_apply_readiness.context.tun2proxy_path.as_ref().map(|path| path.display().to_string()),
                    "mullvad_tunnel_interface": wfp_apply_readiness.context.mullvad_tunnel_interface.as_ref(),
                    "mullvad_tunnel_interface_index": wfp_apply_readiness.context.mullvad_tunnel_interface_index,
                    "mullvad_tunnel_interface_index_error": wfp_apply_readiness.context.mullvad_tunnel_interface_index_error.as_ref(),
                    "mullvad_endpoint_ip": wfp_apply_readiness.context.mullvad_endpoint_ip.as_ref(),
                    "mullvad_endpoint_ip_error": wfp_apply_readiness.context.mullvad_endpoint_ip_error.as_ref(),
                },
                "apply_readiness_blockers": wfp_apply_readiness.blockers,
                "error": error.to_string(),
            }),
        }
    );
}

#[cfg(target_os = "windows")]
fn print_windows_wfp_wintun_selftest_json(proxy_ip: Option<&str>, interface: Option<&str>) {
    let Some(interface) = interface else {
        println!(
            "{}",
            serde_json::json!({
                "ok": false,
                "error": "--interface <adapter name> is required for the Wintun egress self-test"
            })
        );
        return;
    };
    let mullvad = proxy_platform_windows::mullvad_status();
    let firewall = proxy_platform_windows::firewall_preflight();
    let wfp_exception_plan = proxy_platform_windows::wfp_exception_plan(&mullvad, &firewall);
    let wfp_operation_plan = proxy_platform_windows::wfp_operation_plan(&wfp_exception_plan);
    let wfp_apply_context = proxy_platform_windows::wfp_apply_context_for_mullvad_with_paths(
        proxy_ip,
        &mullvad,
        wfp_exception_plan.app_path.clone(),
        wfp_exception_plan.tun2proxy_path.clone(),
    );
    let wfp_apply_readiness = proxy_platform_windows::wfp_apply_readiness_with_context(
        &wfp_exception_plan,
        &wfp_operation_plan,
        &wfp_apply_context,
    );
    let report = proxy_platform_windows::wintun_egress_permit_selftest(
        &wfp_operation_plan,
        &wfp_apply_readiness,
        interface,
    );
    println!(
        "{}",
        serde_json::json!({
            "ok": report.ok,
            "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV,
            "interface": report.interface,
            "luid": report.luid,
            "luid_hex": report.luid.map(|luid| format!("0x{luid:016x}")),
            "luid_error": report.luid_error,
            "phase1_status": report.phase1_status,
            "phase1_errors": report.phase1_errors,
            "wintun_applied": report.wintun_applied,
            "wintun_error": report.wintun_error,
            "rollback_status": report.rollback_status,
            "rollback_errors": report.rollback_errors,
        })
    );
}

/// End-to-end Z4 verification: bring up the full Windows TUN session (WFP exception +
/// tun2proxy + Wintun egress permit), then prove that this process — an ordinary app whose
/// traffic is routed into the proxy Wintun — can still reach the internet while Mullvad's
/// killswitch is active, and report the observed exit IP. Always tears the session back down.
#[cfg(target_os = "windows")]
fn print_windows_tun_session_e2e_json(hold_seconds: u64, probe_url: &str, profile_selector: Option<&str>) {
    let config = match load_or_default_config() {
        Ok(config) => config,
        Err(error) => {
            println!(
                "{}",
                serde_json::json!({ "ok": false, "phase": "config", "error": error.to_string() })
            );
            return;
        }
    };
    let selector = profile_selector
        .map(|value| value.to_string())
        .or_else(|| config.selected_profile_id.clone())
        .or_else(|| config.active_profile_id.clone())
        .or_else(|| config.profiles.first().map(|profile| profile.id.clone()));
    let mut profile = match config.resolve_profile_by_selector(selector.as_deref()) {
        Ok(profile) => profile,
        Err(error) => {
            println!(
                "{}",
                serde_json::json!({ "ok": false, "phase": "resolve_profile", "error": error.to_string() })
            );
            return;
        }
    };
    // This test only exercises the TUN path; force it regardless of the saved routing mode.
    profile.routing_mode = RoutingMode::Tun;

    let mutation_enabled = std::env::var(proxy_platform_windows::ENABLE_WFP_MUTATION_ENV)
        .map(|value| value == "1")
        .unwrap_or(false);

    let start = proxy_platform_windows::start_tun_session(&profile);
    let (start_value, started) = match &start {
        Ok(status) => (namespace_status_json(status), status.state == "connected"),
        Err(error) => (serde_json::json!({ "error": error.to_string() }), false),
    };

    // Self-probe only makes sense if the session actually came up.
    let mut exit_ip: Option<String> = None;
    let mut probe_error: Option<String> = None;
    let mut probe_attempts = 0u32;
    if started {
        match reqwest::blocking::Client::builder()
            .timeout(std::time::Duration::from_secs(10))
            .build()
        {
            Ok(client) => {
                let deadline_attempts = (hold_seconds / 2).max(1) as u32 + 1;
                for attempt in 0..deadline_attempts {
                    probe_attempts = attempt + 1;
                    match client.get(probe_url).send().and_then(|response| response.text()) {
                        Ok(body) => {
                            exit_ip = Some(body.trim().to_string());
                            probe_error = None;
                            break;
                        }
                        Err(error) => {
                            probe_error = Some(error.to_string());
                            std::thread::sleep(std::time::Duration::from_secs(2));
                        }
                    }
                }
            }
            Err(error) => probe_error = Some(format!("failed to build HTTP client: {error}")),
        }
    }

    // Always tear the session back down, even if the probe failed.
    let stop = proxy_platform_windows::stop_tun_session();
    let stop_value = match &stop {
        Ok(status) => namespace_status_json(status),
        Err(error) => serde_json::json!({ "error": error.to_string() }),
    };

    let ok = started && exit_ip.is_some() && stop.is_ok();
    println!(
        "{}",
        serde_json::json!({
            "ok": ok,
            "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV,
            "mutation_enabled": mutation_enabled,
            "profile_name": profile.name,
            "proxy_host": profile.endpoint.host,
            "probe_url": probe_url,
            "probe_attempts": probe_attempts,
            "exit_ip": exit_ip,
            "probe_error": probe_error,
            "session_started": started,
            "start": start_value,
            "stop": stop_value,
        })
    );
}

/// Reproduce the GUI's live behavior: start a TUN session, then repeatedly poll
/// `tun_status()` exactly like the `status` command does on every frontend tick.
/// The e2e command never polls, so the live path (`reconcile_proxy_vpn_route` +
/// `vpn_chain_block_reason` -> possible "blocked" -> auto-stop) is only exercised
/// here. If any poll reports something other than "connected", that is the GUI bug.
#[cfg(target_os = "windows")]
fn print_windows_tun_status_poll_json(polls: u32, interval_ms: u64, profile_selector: Option<&str>) {
    let config = match load_or_default_config() {
        Ok(config) => config,
        Err(error) => {
            println!(
                "{}",
                serde_json::json!({ "ok": false, "phase": "config", "error": error.to_string() })
            );
            return;
        }
    };
    let selector = profile_selector
        .map(|value| value.to_string())
        .or_else(|| config.selected_profile_id.clone())
        .or_else(|| config.active_profile_id.clone())
        .or_else(|| config.profiles.first().map(|profile| profile.id.clone()));
    let mut profile = match config.resolve_profile_by_selector(selector.as_deref()) {
        Ok(profile) => profile,
        Err(error) => {
            println!(
                "{}",
                serde_json::json!({ "ok": false, "phase": "resolve_profile", "error": error.to_string() })
            );
            return;
        }
    };
    profile.routing_mode = RoutingMode::Tun;

    let start = proxy_platform_windows::start_tun_session(&profile);
    let (start_value, started) = match &start {
        Ok(status) => (namespace_status_json(status), status.state == "connected"),
        Err(error) => (serde_json::json!({ "error": error.to_string() }), false),
    };

    // Exercise the exact exit-IP lookup the GUI poller uses, so we verify the
    // TUN-mode (direct client + DNS-free trace) path end-to-end.
    let exit_status = if started {
        Some(crate::geo::lookup_exit_status(&profile, &config.tray_settings))
    } else {
        None
    };
    let exit_status_value = exit_status.as_ref().map(|status| {
        serde_json::json!({
            "exit_ip": status.exit_ip,
            "country_code": status.country_code,
            "country_flag": status.country_flag,
            "lookup_error": status.lookup_error,
        })
    });

    // DNS diagnosis: resolve a hostname through the OS resolver (which harden_dns
    // points at the virtual resolver 10.0.0.1) and separately query 10.0.0.1:53
    // directly via UDP, so we can tell whether the virtual DNS responds at all and
    // whether name resolution is blocked vs. the resolved IP being unroutable.
    let dns_probe = if started {
        use std::net::ToSocketAddrs;
        let os_resolve = match ("api.ipify.org", 443u16).to_socket_addrs() {
            Ok(addrs) => {
                let ips: Vec<String> = addrs.map(|a| a.ip().to_string()).collect();
                serde_json::json!({ "ok": true, "resolved": ips })
            }
            Err(error) => serde_json::json!({ "ok": false, "error": error.to_string() }),
        };
        Some(serde_json::json!({
            "os_resolver": os_resolve,
            "udp_10_0_0_1": dns_query_udp("10.0.0.1:53", "api.ipify.org"),
            "udp_mullvad_10_64_0_1": dns_query_udp("10.64.0.1:53", "api.ipify.org"),
            "udp_external_1_1_1_1": dns_query_udp("1.1.1.1:53", "api.ipify.org"),
        }))
    } else {
        None
    };

    // Prove the local->remote-proxy hop rides INSIDE the Mullvad tunnel: generate
    // sustained traffic so tun2proxy holds a connection open to the proxy server,
    // then inspect that socket's LOCAL source address. It must be the Mullvad
    // tunnel-internal IP (not a physical interface), which means the proxy
    // connection is encapsulated by Mullvad rather than leaking around it.
    let proxy_link = if started {
        let proxy_ip = start.as_ref().ok().and_then(|s| s.proxy_ip.clone());
        if let Some(proxy_ip) = proxy_ip {
            // Sustained traffic in a background thread so the proxy socket stays up
            // while we snapshot the TCP table.
            let traffic = std::thread::spawn(|| {
                if let Ok(client) = reqwest::blocking::Client::builder()
                    .timeout(std::time::Duration::from_secs(6))
                    .build()
                {
                    for _ in 0..6 {
                        let _ = client
                            .get("https://speed.cloudflare.com/__down?bytes=4000000")
                            .send()
                            .and_then(|r| r.bytes());
                    }
                }
            });
            std::thread::sleep(std::time::Duration::from_millis(1500));
            let snapshot = tcp_connections_to(&proxy_ip);
            let _ = traffic.join();
            Some(serde_json::json!({
                "proxy_ip": proxy_ip,
                "mullvad_tunnel_hint": "Mullvad source IP = inside tunnel; physical NIC IP = leak",
                "connections": snapshot,
            }))
        } else {
            None
        }
    } else {
        None
    };

    let mut poll_states: Vec<serde_json::Value> = Vec::new();
    if started {
        for index in 0..polls {
            std::thread::sleep(std::time::Duration::from_millis(interval_ms));
            match proxy_platform_windows::tun_status() {
                Ok(status) => poll_states.push(serde_json::json!({
                    "poll": index + 1,
                    "state": status.state,
                    "proxy_uplink_interface": status.proxy_uplink_interface,
                    "host_vpn_interface": status.host_vpn_interface,
                    "last_reason": status.last_reason,
                    "last_error": status.last_error,
                })),
                Err(error) => poll_states.push(serde_json::json!({
                    "poll": index + 1,
                    "error": error.to_string(),
                })),
            }
        }
    }

    let stayed_connected = started
        && poll_states.iter().all(|poll| {
            poll.get("state").and_then(|s| s.as_str()) == Some("connected")
        });

    let stop = proxy_platform_windows::stop_tun_session();
    let stop_value = match &stop {
        Ok(status) => namespace_status_json(status),
        Err(error) => serde_json::json!({ "error": error.to_string() }),
    };

    println!(
        "{}",
        serde_json::json!({
            "ok": stayed_connected && stop.is_ok(),
            "session_started": started,
            "stayed_connected": stayed_connected,
            "profile_name": profile.name,
            "start": start_value,
            "exit_status": exit_status_value,
            "dns_probe": dns_probe,
            "proxy_link": proxy_link,
            "polls": poll_states,
            "stop": stop_value,
        })
    );
}

/// Snapshot established TCP connections to `proxy_ip` via Get-NetTCPConnection,
/// reporting each socket's local (source) address so we can confirm the proxy hop
/// originates from the Mullvad tunnel interface, not a physical NIC.
#[cfg(target_os = "windows")]
fn tcp_connections_to(proxy_ip: &str) -> serde_json::Value {
    let script = format!(
        "Get-NetTCPConnection -RemoteAddress '{proxy_ip}' -ErrorAction SilentlyContinue | \
         ForEach-Object {{ \"{{0}}|{{1}}|{{2}}|{{3}}|{{4}}\" -f \
         $_.LocalAddress,$_.LocalPort,$_.RemotePort,$_.State,\
         (Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue).ProcessName }}"
    );
    let output = crate::util::console_hidden_command("powershell")
        .args(["-NoProfile", "-Command", &script])
        .output();
    match output {
        Ok(out) => {
            let text = String::from_utf8_lossy(&out.stdout);
            let rows: Vec<serde_json::Value> = text
                .lines()
                .filter(|line| !line.trim().is_empty())
                .map(|line| {
                    let f: Vec<&str> = line.split('|').collect();
                    serde_json::json!({
                        "local_address": f.first().copied().unwrap_or(""),
                        "local_port": f.get(1).copied().unwrap_or(""),
                        "remote_port": f.get(2).copied().unwrap_or(""),
                        "state": f.get(3).copied().unwrap_or(""),
                        "process": f.get(4).copied().unwrap_or(""),
                    })
                })
                .collect();
            serde_json::json!(rows)
        }
        Err(error) => serde_json::json!({ "error": error.to_string() }),
    }
}

/// Send a minimal DNS A-query for `host` to `server` over UDP and report the
/// outcome. Used to test whether tun2proxy's virtual resolver at 10.0.0.1 answers
/// at all (vs. the query being blocked, e.g. by Mullvad's DNS enforcement).
#[cfg(target_os = "windows")]
fn dns_query_udp(server: &str, host: &str) -> serde_json::Value {
    use std::net::UdpSocket;
    let mut query = Vec::new();
    query.extend_from_slice(&[0x12, 0x34]); // id
    query.extend_from_slice(&[0x01, 0x00]); // flags: recursion desired
    query.extend_from_slice(&[0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]); // 1 question
    for label in host.split('.') {
        query.push(label.len() as u8);
        query.extend_from_slice(label.as_bytes());
    }
    query.push(0);
    query.extend_from_slice(&[0x00, 0x01]); // type A
    query.extend_from_slice(&[0x00, 0x01]); // class IN

    let socket = match UdpSocket::bind("0.0.0.0:0") {
        Ok(socket) => socket,
        Err(error) => return serde_json::json!({ "ok": false, "phase": "bind", "error": error.to_string() }),
    };
    let _ = socket.set_read_timeout(Some(std::time::Duration::from_secs(4)));
    if let Err(error) = socket.send_to(&query, server) {
        return serde_json::json!({ "ok": false, "phase": "send", "error": error.to_string() });
    }
    let mut buf = [0u8; 512];
    match socket.recv_from(&mut buf) {
        Ok((len, _)) => {
            let answers = if len >= 8 { ((buf[6] as u16) << 8) | buf[7] as u16 } else { 0 };
            serde_json::json!({ "ok": true, "response_bytes": len, "answer_count": answers })
        }
        Err(error) => serde_json::json!({ "ok": false, "phase": "recv", "error": error.to_string() }),
    }
}

#[cfg(target_os = "windows")]
fn namespace_status_json(status: &proxy_core::NamespaceSessionStatus) -> serde_json::Value {
    serde_json::json!({
        "state": status.state,
        "profile_name": status.profile_name,
        "proxy_ip": status.proxy_ip,
        "tun2proxy_pid": status.tun2proxy_pid,
        "host_vpn_interface": status.host_vpn_interface,
        "proxy_uplink_interface": status.proxy_uplink_interface,
        "last_error": status.last_error,
        "last_reason": status.last_reason,
        "wfp_filter_count": status.wfp_filters.len(),
    })
}

#[cfg(target_os = "windows")]
fn windows_z4_guard_json(
    status: &proxy_platform_windows::WindowsMullvadStatus,
) -> serde_json::Value {
    let connected = status
        .state
        .as_deref()
        .map(|state| state.to_ascii_lowercase().starts_with("connected"))
        .unwrap_or(false);

    if connected {
        let endpoint = status
            .endpoint_address
            .as_deref()
            .or(status.relay_hostname.as_deref())
            .unwrap_or("unknown endpoint");
        return serde_json::json!({
            "status": "blocked",
            "blocked": true,
            "reason": format!("Mullvad is connected ({endpoint}). Windows Z4 requires the scoped WFP kill-switch exception before TUN routing can start. The exception is applied only when SOCKS5PROXY_ENABLE_WFP_MUTATION=1 is set in an elevated guarded session."),
            "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV
        });
    }

    if let Some(error) = status.error.as_deref() {
        return serde_json::json!({
            "status": "warn",
            "blocked": false,
            "reason": format!("Mullvad status could not be verified: {error}"),
            "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV
        });
    }

    serde_json::json!({
        "status": "pass",
        "blocked": false,
        "reason": "No connected Mullvad tunnel is active; guarded Z2 live testing is not blocked by the Z4 WFP guard.",
        "mutation_env": proxy_platform_windows::ENABLE_WFP_MUTATION_ENV
    })
}

#[cfg(target_os = "windows")]
fn guard_windows_wireguard_killswitch() -> Result<(), String> {
    let status = proxy_platform_windows::wireguard_status();
    if status.interfaces.is_empty() {
        return Ok(());
    }

    if status.locked_down == Some(true) {
        let reason = status
            .lockdown_reason
            .as_deref()
            .unwrap_or("WireGuard firewall block rules are active");
        return Err(format!(
            "Windows Z3 with WireGuard kill-switch enabled is intentionally blocked in V1. Disable WireGuard's \"Block untunneled traffic\" option for Z3, or use the future Z3b/Z4 WFP exception path. Detected: {reason}"
        ));
    }

    Ok(())
}

fn init_logging() {
    use tracing_subscriber::EnvFilter;
    let filter =
        EnvFilter::try_from_env("SOCKS5PROXY_LOG").unwrap_or_else(|_| EnvFilter::new("info"));
    let _ = tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_target(false)
        .with_writer(std::io::stderr)
        .try_init();
}

fn load_or_default_config() -> Result<AppConfig, ConfigError> {
    match AppConfig::load_default_path() {
        Ok(config) => Ok(config),
        Err(ConfigError::Io(error)) if error.kind() == std::io::ErrorKind::NotFound => {
            Ok(AppConfig::default())
        }
        Err(error) => Err(error),
    }
}

fn start_saved_active_profile(app: &AppHandle) -> Result<(), String> {
    let config = load_or_default_config().map_err(|e| e.to_string())?;
    let profile_id = config
        .selected_profile_id
        .clone()
        .or_else(|| config.active_profile_id.clone())
        .or_else(|| config.profiles.first().map(|profile| profile.id.clone()))
        .ok_or_else(|| "no saved profile is available to connect".to_string())?;
    let tray = app.state::<TrayHandles>();
    let state = app.state::<SharedRuntimeState>();
    start_proxy_background(app, tray.inner(), state.inner(), config, profile_id)
}

fn ensure_manage_window(app: &AppHandle) -> tauri::Result<()> {
    if app.get_webview_window("manage").is_some() {
        return Ok(());
    }

    WebviewWindowBuilder::new(app, "manage", WebviewUrl::App("index.html".into()))
        .title("SOCKS5 Proxy Settings")
        .inner_size(980.0, 760.0)
        .visible(false)
        .build()?;

    Ok(())
}

fn set_runtime_error(app: &AppHandle, message: &str) {
    if let Some(runtime_state) = app.try_state::<SharedRuntimeState>() {
        if let Ok(mut runtime) = runtime_state.lock() {
            runtime.connection_state = ConnectionState::Error;
            runtime.last_error = Some(message.to_string());
            let snapshot = RuntimeSnapshot::from(&*runtime);
            if let Some(tray) = app.try_state::<TrayHandles>() {
                update_tray_ui(app, tray.inner(), &snapshot);
            }
        }
    }
    tracing::error!(error = %message, "tray action failed");
}

fn refresh_direct_exit_status_background(
    app: AppHandle,
    tray: TrayHandles,
    state: SharedRuntimeState,
    tray_settings: TraySettings,
) {
    if !tray_settings.exit_ip_lookup_enabled {
        return;
    }

    std::thread::spawn(move || {
        let should_refresh = state
            .lock()
            .map(|runtime| runtime.connection_state == ConnectionState::Stopped)
            .unwrap_or(false);
        if !should_refresh {
            return;
        }

        let exit_status = lookup_exit_status_direct(&tray_settings);
        let snapshot = {
            let mut runtime = match state.lock() {
                Ok(runtime) => runtime,
                Err(_) => return,
            };
            if runtime.connection_state != ConnectionState::Stopped {
                return;
            }
            runtime.exit_status = exit_status;
            RuntimeSnapshot::from(&*runtime)
        };
        update_tray_ui(&app, &tray, &snapshot);
    });
}

fn sync_runtime_with_tun_status(runtime: &mut RuntimeState) {
    match tun_backend::status() {
        Ok(status) => {
            // A connect runs on a background thread; until it finishes start_tun_session
            // and stores the session, the slot is empty and tun_status() reports
            // "stopped". While we are still Rebinding, that means "starting", not
            // "disconnected" — don't flip the UI to "Disconnected" for those seconds.
            // The start thread will move us to Connected (success) or Error (failure).
            if status.state == "stopped"
                && runtime.connection_state == ConnectionState::Rebinding
            {
                return;
            }
            let blocked = status.state == "blocked";
            apply_tun_daemon_status(runtime, &status);
            if blocked {
                let _ = tun_backend::stop();
                if let Some(artifacts) = runtime.runtime_artifacts.take() {
                    if let Err(error) = cleanup_runtime_artifacts(&artifacts) {
                        runtime.connection_state = ConnectionState::Error;
                        runtime.last_error = Some(format!(
                            "Windows TUN was blocked for VPN safety, but cleanup failed: {error}"
                        ));
                    }
                }
                runtime.current_session_id = None;
            }
        }
        Err(error) => {
            // The daemon is unreachable (stopped or crashed) while we still believe a
            // TUN session is active. Reflect that as an error state instead of bubbling
            // the error up: `status` is polled by the GUI, which swallows command
            // errors, so propagating here would freeze the UI on the last good
            // (Connected) snapshot. Surfacing Error keeps the GUI and tray consistent
            // and self-heals once the daemon answers again.
            runtime.connection_state = ConnectionState::Error;
            runtime.last_error = Some(format!("socks5proxy daemon is not reachable: {error}"));
            runtime.traffic_flow = network::build_traffic_flow(
                runtime.active_profile.as_ref(),
                &runtime.vpn_status,
                runtime.connection_state,
            );
        }
    }
}

fn apply_tun_daemon_status(
    runtime: &mut RuntimeState,
    status: &proxy_core::NamespaceSessionStatus,
) {
    runtime.connection_state = match status.state.as_str() {
        "connected" => ConnectionState::Connected,
        "blocked" => ConnectionState::Blocked,
        "error" => ConnectionState::Error,
        "starting" => ConnectionState::Rebinding,
        _ => ConnectionState::Stopped,
    };
    runtime.last_error = status.last_error.clone();
    runtime.vpn_status.state = status.state.clone();
    runtime.vpn_status.vpn_interface = status.host_vpn_interface.clone();
    runtime.vpn_status.proxy_uplink_interface = status.proxy_uplink_interface.clone();
    runtime.vpn_status.last_reason = status.last_reason.clone();
    runtime.traffic_flow = network::build_traffic_flow(
        runtime.active_profile.as_ref(),
        &runtime.vpn_status,
        runtime.connection_state,
    );
    if let Some(artifacts) = runtime.runtime_artifacts.as_mut() {
        artifacts.proxy_pid = status.tun2proxy_pid;
        artifacts.bound_vpn_interface = status.host_vpn_interface.clone();
        artifacts.pinned_proxy_routes = status.pinned_proxy_routes.clone();
        artifacts.wfp_filters = status.wfp_filters.clone();
    }
}
